import streamlit as st
import pandas as pd
import joblib
import os

st.write("__file__ =", __file__)
st.write("dirname =", os.path.dirname(__file__))
st.write("files =", os.listdir(os.path.dirname(__file__)))
model_path = os.path.join(os.path.dirname(__file__), "solar_power_model.pkl")
st.write("model path =", model_path)
model = joblib.load(model_path)

st.set_page_config(
    page_title="Solar Power Predictor",
    page_icon="☀️",
    layout="centered"
)


st.title("☀️ Solar Power Generation Predictor")
st.markdown(
    "Predict solar power generation using weather and environmental parameters."
)

st.divider()


st.subheader("📊 Weather Parameters")

col1, col2 = st.columns(2)

with col1:

    windspeed = st.number_input(
        "🌬 Wind Speed (m/s)",
        min_value=0.0,
        max_value=11.0,
        value=2.5,
        step=0.1
    )

    sunshine = st.slider(
        "☀️ Sunshine (minutes)",
        min_value=0,
        max_value=60,
        value=30
    )

    airpressure = st.number_input(
        "🌍 Air Pressure (hPa)",
        min_value=965.0,
        max_value=1048.0,
        value=1011.0,
        step=0.1
    )

    radiation = st.number_input(
        "🔆 Solar Radiation",
        min_value=-10.0,
        max_value=900.0,
        value=100.0,
        step=0.1
    )

with col2:

    temperature = st.number_input(
        "🌡 Air Temperature (°C)",
        min_value=-13.0,
        max_value=28.0,
        value=7.0,
        step=0.1
    )

    humidity = st.number_input(
        "💧 Relative Air Humidity (%)",
        min_value=13.0,
        max_value=100.0,
        value=77.0
    )

    hour = st.slider(
        "🕒 Hour of Day",
        min_value=0,
        max_value=23,
        value=12
    )

    month = st.selectbox(
        "📅 Month",
        options=list(range(1, 13)),
        index=5
    )

st.divider()


if st.button("🚀 Predict Solar Power", use_container_width=True):

    input_data = pd.DataFrame(
        [[
            windspeed,
            sunshine,
            airpressure,
            radiation,
            temperature,
            humidity,
            hour,
            month
        ]],
        columns=[
            'WindSpeed',
            'Sunshine',
            'AirPressure',
            'Radiation',
            'AirTemperature',
            'RelativeAirHumidity',
            'Hour',
            'Month'
        ]
    )

    prediction = model.predict(input_data)

    st.success(
        f"⚡ Predicted Solar Power Generation: {prediction[0]:.2f} W"
    )

    st.metric(
        label="Predicted Output",
        value=f"{prediction[0]:.2f} W"
    )

st.divider()
st.warning("⚠️ Predicted values are estimates generated by an AI model trained on historical weather and solar production data. Actual solar power output may differ due to environmental and operational factors.")
st.caption("Made with ❤️ by Akshat Mehrotra")